package org.learning.core;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.*;

import static org.assertj.core.api.Assertions.assertThat;

class DsaCollectionsTest {

    @DisplayName("HashMap")
    @Test
    void testHaspMap(){
        // size, isEmpty, get, containsKey
        {
            var m = getHashMap();

            assertThat(m.size()).isEqualTo(3);
            assertThat(m.isEmpty()).isFalse();

            assertThat(m.get('a')).isEqualTo(1); // Key, value present
            assertThat(m.get('k')).isNull(); // Key mapped to null value
            assertThat(m.get(null)).isEqualTo(2); // null key mapped to value
            assertThat(m.get('y')).isNull(); // key not mapped/present

            assertThat(m.containsKey(null)).isTrue(); // Check if key present or not
        }
        // put, putAll, remove, clear, entrySet
        {
            var m = getHashMap();

            // Replaces value if present or creates new key value pair,
            // returns the previous value associated with key if key was already mapped
            assertThat(m.put(null, 3)).isEqualTo(2);

            // Replace entries if already present
            m.putAll(getHashMap());

            assertThat(m.remove('a')).isEqualTo(1); // previously mapped kay
            assertThat(m.remove('k')).isNull(); // null, as key was mapped to null
            assertThat(m.remove('y')).isNull(); // null, as key not present

            m.clear(); // Clear all entries
            m.putAll(getHashMap()); // Create entry if not present, replace value if key us present

            // Get, Set of all entries
            Set<Map.Entry<Character, Integer>> set = m.entrySet();
        }
        // computeIfAbsent
        {
            var m = getHashMap();
            /*
                Compute value for a key, when key is not present or mapped to null.
                if mapping function itself return null, do nothing.
                Commonly used to initialize a key with a value (new HashSet, new ArrayList)
                returns currently computed value.
            */
            assertThat(m.computeIfAbsent('k', key -> 3)).isEqualTo(3); // Updated the value, As it was mapped to null.
            assertThat(m.computeIfAbsent('y', key -> 6)).isEqualTo(6); // Add key value pair entry as key was not present
            assertThat(m.get('k')).isEqualTo(3);
            assertThat(m.get('y')).isEqualTo(6);

            assertThat(m.computeIfAbsent('a', key -> 3)).isEqualTo(1);
            assertThat(m.computeIfAbsent('a', key -> null)).isEqualTo(1);
            assertThat(m.get('a')).isEqualTo(1); // Above two operations does nothing as key was mapped to non-null value.
        }
        // computeIfPresent
        {
            var m = getHashMap();
            /*
                Compute value for a key when it's associated with non-null value.
                If remapping function returns null, then entry is removed
                return latest computed value
             */
            assertThat(m.computeIfPresent('a', (key, value) -> value + 1)).isEqualTo(2);

            // Below operations does not do anything as value associated with the key is null or key itself is not present
            assertThat(m.computeIfPresent('k', (key, value) -> value + 1)).isNull();
            assertThat(m.computeIfPresent('y', (key, value) -> value + 1)).isNull();
        }
        // compute
        {
            /*
                If the specified key is not already associated with a value or is associated with null,
                associates it with the non-null value generated by remapping function.
                If the remapping function returns null, the mapping is removed
                Returns newly computed value
             */
            var m = getHashMap();
            assertThat(m.compute('k', (key, value) -> Objects.isNull(value) ? 1 : value + 1)).isEqualTo(1);
            assertThat(m.compute('y', (key, value) -> Objects.isNull(value) ? 1 : value + 1)).isEqualTo(1);
            assertThat(m.containsKey('y')).isTrue();
            assertThat(m.compute('a', (key, value) -> null)).isNull();
            assertThat(m.containsKey('a')).isFalse();
        }
        // merge
        {
            /*
                If the specified key is not already associated with a value or is associated with null, associates it with the given non-null value.
                Otherwise, replaces the associated value with the results of the given remapping function,
                or removes if the result is null.
                Returns newly computed value.
             */
            var m = getHashMap();
            assertThat(m.merge('a', 1, (oldValue, newValue) -> oldValue + newValue)).isEqualTo(2);
            assertThat(m.merge('k', 1, (oldValue, newValue) -> oldValue + newValue)).isEqualTo(1);
            assertThat(m.merge( null, 1, (oldValue, newValue) -> null)).isNull(); // Remove null key, as function returned null
            assertThat(m.containsKey(null)).isFalse();
        }
        // Ways to iterate
        {
            var m = getHashMap();

            // Iterate (This is more efficient than looping over keys and calling get() on each.)
            for(var entry : m.entrySet()){
                System.out.println(entry);
            }

            // java 8 forEach
            m.forEach((key, value) -> System.out.println(key + "=" + value));

            // Streams API
            m.entrySet().stream()
                    .filter(entry -> entry.getKey() > 1)
                    .forEach(System.out::println);

            // Iterate over only key or values
            for(var key : m.keySet()) {
                System.out.println(key);
            }
            for(var value : m.values()) { // .values return a collection
                System.out.println(value);
            }

        }
    }

    private Map<Character, Integer> getHashMap(){
        var m = new HashMap<Character, Integer>();

        m.put('a', 1);
        m.put('k', null);
        m.put(null, 2);

        return new HashMap<>(m);
    }

    /**
     * null key not permitted
     */
    @DisplayName("TreeMap")
    @Test
    void testTreeMap(){
        // lower, higher, ceiling, floor, first, last, pollFirst, pollLast
        {
            var m = getTreeMap();

            var e = m.firstEntry(); // returns null, if map is empty
            assertThat(e.getKey()).isEqualTo(1); assertThat(e.getValue()).isNull();
            e = m.lastEntry(); // returns null, if map is empty
            assertThat(e.getKey()).isEqualTo(10); assertThat(e.getValue()).isEqualTo(15);

            // returns null if such entry not present, lowerKey, higherKey methods are also there
            e = m.lowerEntry(3); assertThat(e.getKey()).isEqualTo(1);
            e = m.higherEntry(3); assertThat(e.getKey()).isEqualTo(10);

            // returns null if such entry not present, floorKey, ceilingKey methods are also there
            e = m.floorEntry(2); assertThat(e.getKey()).isEqualTo(1);
            e = m.ceilingEntry(3); assertThat(e.getKey()).isEqualTo(3);


            // Below method returns the first/last entry which were removed or return null if map is empty
            e = m.pollFirstEntry(); assertThat(e.getKey()).isEqualTo(1);
            e = m.pollLastEntry(); assertThat(e.getKey()).isEqualTo(10);
        }
        // headMap, tailMap, subMap
        {
            var m = getTreeMap();

            var headMap = m.headMap(2, true); assertThat(headMap).containsEntry(1, null);
            var subMap = m.subMap(2, true, 9, true); assertThat(subMap).containsEntry(3, 1);
            var tailMap = m.tailMap(2, true); assertThat(tailMap).containsEntry(3, 1).containsEntry(10, 15);
        }
        // Ways to iterate
        {
            var m = getTreeMap();

            // Iterate in ascending order
            for(var entry : m.entrySet()){
                System.out.println(entry);
            }

            // java 8 forEach
            m.forEach((key, value) -> System.out.println(key + "=" + value));

            // Iterate in descending order
            for(var entry : m.descendingMap().entrySet()){
                System.out.println(entry);
            }

            // Iterating tailMap, subMap, headMap
            for(var entry : m.subMap(2, true, 16, true).entrySet()){
                System.out.println(entry);
            }

            // Streams API
            m.entrySet().stream()
                    .filter(entry -> entry.getKey() > 1)
                    .forEach(System.out::println);

            // Iterate over only key or values
            for(var key : m.keySet()) {
                System.out.println(key);
            }
            for(var value : m.values()) { // .values return a collection
                System.out.println(value);
            }

        }
    }

    private TreeMap<Integer, Integer> getTreeMap(){
        var m = new TreeMap<Integer, Integer>();
        m.put(3, 1);
        m.put(10, 15);
        m.put(1, null);
//        m.put(null, 0); null key not permitted
        return new TreeMap<>(m);
    }

    /**
     *  Uses HashMap internally.
     *  One null element allowed
     */
    @DisplayName("HashSet")
    @Test
    void testHashSet(){
        var s = new HashSet<Integer>();

        assertThat(s.size()).isEqualTo(0);
        assertThat(s.isEmpty()).isTrue();

        assertThat(s.add(1)).isTrue();
        assertThat(s.add(2)).isTrue();
        assertThat(s.add(null)).isTrue(); // Allows null
        assertThat(s.add(1)).isFalse(); // Returns false if set already contains the element

        assertThat(s.contains(null)).isTrue();
        assertThat(s.contains(10)).isFalse();

        assertThat(s.remove(null)).isTrue();
        assertThat(s.remove(10)).isFalse();

        // Refer TreeSet way of iterating to know about ways of iterating
    }

    /**
     * Uses TreeMap internally.
     * Does not allow null.
     */
    @DisplayName("TreeSet")
    @Test
    void testTreeSet(){
        // subSet, headSet, tailSet, lower, higher, ceiling, floor, pollFirst, pollLast, first, last
        {
            var s = new TreeSet<>(Set.of(5, 4, 3, 2, 1));

            var subSet = s.subSet(2, true, 4, true); assertThat(subSet).containsSequence(2, 3, 4);
            var headSet = s.headSet(2, true); assertThat(headSet).containsSequence(1, 2);
            var tailSet = s.tailSet(2, true); assertThat(tailSet).containsSequence(2, 3, 4, 5);

            // If not present return null
            assertThat(s.lower(3)).isEqualTo(2);
            assertThat(s.higher(3)).isEqualTo(4);
            assertThat(s.ceiling(3)).isEqualTo(3);
            assertThat(s.floor(3)).isEqualTo(3);

            // NoSuchElementException - if this set is empty
            assertThat(s.first()).isEqualTo(1);
            assertThat(s.last()).isEqualTo(5);

            // If empty return null
            assertThat(s.pollFirst()).isEqualTo(1);
            assertThat(s.pollLast()).isEqualTo(5);
        }
        // Ways of iterating
        {
            var s = new TreeSet<>(Set.of(5, 4, 3, 2, 1));

            // for each loop
            for(var ele : s){
                System.out.println(ele);
            }

            // java 8 for each
            s.forEach(System.out::println);

            // Streams API
            s.stream().filter(ele -> ele > 3).forEach(System.out::println);

            // Descending order
            for(var ele : s.descendingSet()){
                System.out.println(ele);
            }

            // Iterating headSet, tailSet, subSet
            for(var ele : s.tailSet(3, true)){
                System.out.println(ele);
            }

            // Reverse and then iterate over tailsSet
            for(var ele : s.descendingSet().tailSet(3, true)){
                System.out.println(ele);
            }

            s.descendingSet()
                    .tailSet(3, true)
                    .stream()
                    .forEach(System.out::println);

        }
    }

}
